### ISSUE TITLE
2 Emotiva xmc 2

### ISSUE THREAD

**Issue by acurafan** [peteS-UK/emotiva#15] opened 2024-11-16 17:03 UTC
I have 2 processors and cant seem to get both working with Home Assistant. Is there any way to get both of them working?

**Comment by peteS-UK** [comment] 2024-11-17 10:50
Yes, right now only one processor is working.  The problem is that rather than reply to a status request on the port from which the connection was made, all processors always reply to a single port.  So, I'd have to understand the sending device in a single listener and then distribute the updates accordingly.  I did start to do this and I don't think it's too hard, but no-one had asked for it and I couldn't do any testing of course.  If you're up for being a guinea pig, I'll try and revisit it, but I'm away at the minute so it'll be a little while.

**Comment by acurafan** [comment] 2024-11-17 11:38
Thanks for confirming this, I have been at it for a while. I don't mind being the guinea pig! I love the integration. No rush

**Comment by peteS-UK** [comment] 2024-12-10 23:34
I'll try and take a look at this in the next couple of weeks.  There is actually some code already for 2 processors, but it's not finished.  Out of curiosity, what happens if you add the 2 processors (maybe discover one and add the second manually) after enabling debug logging - i.e. delete the config you have, reboot HA if you can, enable debug logging, add the 2 processors, and maybe turn them both on via their power button and then turn off debug logging.  I can't test anything, so before I start revisiting this (which I haven't looked at in a long time), it'll be interesting to see the current state of play.

I did modify the listener to capture the source of the notifications but IIRC I need to move the initialistion of the listener to be independent of the device and since I couldn't test it and hadn't been asked, I don't think I ever did it.

**Comment by acurafan** [comment] 2024-12-11 00:38
Hi Pete

I deleted the 1 xmc2 and then added one via discover mode. I then enabled de bugging. I added the second one manually. This is error message that comes up when I toggle the remote on/off slider of the seconed xmc 2 Failed to perform the action remote/turn_on. 'NoneType' object has no attribute 'recv'

I have attached the de bug file for you.

Let me know if you have any questions or need me to try any other options

Thanks,
Larry





________________________________

**Comment by peteS-UK** [comment] 2024-12-11 10:05
Thanks Larry, but I think you forgot to attach the file....

**Comment by acurafan** [comment] 2024-12-11 10:27
Good Morning

Hopefully its there now


________________________________

**Comment by peteS-UK** [comment] 2024-12-11 22:29
> Good Morning Hopefully its there now
> […](#)

Nope - not seeing it.  Could you try posting it directly into github - I see you're replying by email, so maybe attachments don't work for some reason.

**Comment by acurafan** [comment] 2024-12-11 23:57
2024-12-10 19:22:46.069 WARNING (SyncWorker_0) [homeassistant.loader] We
found a custom integration emotiva which has not been tested by Home
Assistant. This component might cause stability problems, be sure to
disable it if you experience issues with Home Assistant
2024-12-10 19:22:46.072 WARNING (SyncWorker_0) [homeassistant.loader] We
found a custom integration hacs which has not been tested by Home
Assistant. This component might cause stability problems, be sure to
disable it if you experience issues with Home Assistant
2024-12-10 19:25:24.985 DEBUG (MainThread) [custom_components.emotiva]
Adding 192.168.1.144 Name: XMC 2 Model: XMC-2 from config
2024-12-10 19:25:24.986 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Stripped Model XMC2
2024-12-10 19:25:24.986 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Sound Modes for XMC-2
2024-12-10 19:25:25.065 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Setting up Notify Listener
2024-12-10 19:25:25.066 CRITICAL (MainThread)
[custom_components.emotiva.emotiva] Cannot bind to local socket 98: Address
in use
2024-12-10 19:25:25.070 CRITICAL (MainThread)
[custom_components.emotiva.emotiva] Cannot connect listener socket 98:
Address in use
2024-12-10 19:25:25.071 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Subscribing to {'input_5', 'power',
'audio_bitstream', 'input_1', 'input_3', 'input_7', 'input_8',
'audio_input', 'volume', 'video_input', 'video_format', 'zone2_power',
'input_6', 'source', 'input_4', 'mode', 'input_2'}
2024-12-10 19:25:25.074 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Connection lost.  Attepting to reconnect
2024-12-10 19:25:25.074 WARNING (MainThread) [py.warnings]
/config/custom_components/emotiva/emotiva.py:327: RuntimeWarning: coroutine
'Emotiva.udp_connect' was never awaited
  self.udp_connect()

2024-12-10 19:25:25.074 CRITICAL (MainThread)
[custom_components.emotiva.emotiva] Unknown error on command socket
reconnection <class 'AttributeError'>
2024-12-10 19:25:25.074 ERROR (MainThread)
[homeassistant.components.media_player] Error adding entity
media_player.emotivaprocessor_2 for domain media_player with platform
emotiva
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1383,
in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/emotiva/media_player.py", line 127, in
async_added_to_hass
    await self._device.async_subscribe_events()
  File "/config/custom_components/emotiva/emotiva.py", line 257, in
async_subscribe_events
    await self._subscribe_events(self._events)
  File "/config/custom_components/emotiva/emotiva.py", line 273, in
_subscribe_events
    await self._async_send_request(msg, ack=True)
  File "/config/custom_components/emotiva/emotiva.py", line 355, in
_async_send_request
    await self._udp_client(req, ack)
  File "/config/custom_components/emotiva/emotiva.py", line 341, in
_udp_client
    resp, remote_addr = await self._udp_stream.recv()
                              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'recv'
2024-12-10 19:26:16.824 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Received notification:
<?xml version="1.0"?>
<emotivaNotify sequence="306">
  <property name="power" value="On" visible="true"/>
  <property name="source_tuner" value="FISION    " visible="true"/>
  <property name="source" value="FISION    " visible="true"/>
  <property name="dim" value="20" visible="true"/>
  <property name="mode" value="Dolby Surround" visible="true"/>
  <property name="selected_mode" value="Auto" visible="true"/>
  <property name="speaker_preset" value="Preset 2" visible="true"/>
  <property name="center" value="  0.0" visible="true"/>
  <property name="subwoofer" value="  0.0" visible="true"/>
  <property name="surround" value="  0.0" visible="true"/>
  <property name="back" value="None" visible="true"/>
  <property name="width" value="None" visible="true"/>
  <property name="height" value="  0.0" visible="true"/>
  <property name="volume" value="-36.0" visible="true"/>
  <property name="loudness" value="Off" visible="true"/>
  <property name="tuner_band" value="FM" visible="true"/>
  <property name="tuner_channel" value="FM 107.90MHz" visible="true"/>
  <property name="tuner_signal" value="Mono   0dBuV" visible="true"/>
  <property name="tuner_program" value="" visible="true"/>
  <property name="tuner_RDS" value="" visible="true"/>
  <property name="audio_input" value="HDMI 1" visible="true"/>
  <property name="audio_bitstream" value="Dolby Plus 5.1" visible="true"/>
  <property name="audio_bits" value="48kHz 20bits" visible="true"/>
  <property name="video_input" value="HDMI 1" visible="true"/>
  <property name="video_format" value="2160P/60" visible="true"/>
  <property name="video_space" value=" 12bits " visible="true"/>
  <property name="input_1" value="FISION    " visible="true"/>
  <property name="input_2" value="BLU RAY   " visible="true"/>
  <property name="input_3" value="XBOX X    " visible="true"/>
  <property name="input_4" value="AMD  7" visible="true"/>
  <property name="input_5" value="FIRE TV" visible="true"/>
  <property name="input_6" value="PHONO     " visible="true"/>
  <property name="input_7" value="Sonos " visible="true"/>
  <property name="input_8" value="" visible="false"/>
  <property name="treble" value="  0.0" visible="true"/>
  <property name="bass" value="  0.0" visible="true"/>
  <property name="mode_auto" value="Auto" visible="true"/>
  <property name="mode_music" value="Music" visible="false"/>
  <property name="mode_movie" value="Movie" visible="false"/>
  <property name="mode_direct" value="Direct" visible="true"/>
  <property name="mode_surround" value="Surround" visible="true"/>
  <property name="mode_ref_stereo" value="Reference Stereo" visible="true"/>
  <property name="mode_dolby" value="Dolby" visible="false"/>
  <property name="mode_dts" value="DTS" visible="false"/>
  <property name="mode_all_stereo" value="All Stereo" visible="true"/>
  <property name="mode_stereo" value="Stereo" visible="true"/>
  <property name="menu" value="Off" visible="true"/>
</emotivaNotify>

2024-12-10 19:26:16.825 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Notify Handler called
2024-12-10 19:26:16.826 DEBUG (MainThread)
[custom_components.emotiva.emotiva] _handle_status called
2024-12-10 19:26:16.826 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: source_tuner
2024-12-10 19:26:16.826 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: dim
2024-12-10 19:26:16.827 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: selected_mode
2024-12-10 19:26:16.827 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: speaker_preset
2024-12-10 19:26:16.827 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: center
2024-12-10 19:26:16.827 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: subwoofer
2024-12-10 19:26:16.827 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: surround
2024-12-10 19:26:16.827 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: back
2024-12-10 19:26:16.827 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: width
2024-12-10 19:26:16.828 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: height
2024-12-10 19:26:16.828 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: loudness
2024-12-10 19:26:16.828 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: tuner_band
2024-12-10 19:26:16.828 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: tuner_channel
2024-12-10 19:26:16.828 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: tuner_signal
2024-12-10 19:26:16.829 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: tuner_program
2024-12-10 19:26:16.829 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: tuner_RDS
2024-12-10 19:26:16.829 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: audio_bits
2024-12-10 19:26:16.829 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: video_space
2024-12-10 19:26:16.829 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: treble
2024-12-10 19:26:16.829 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: bass
2024-12-10 19:26:16.830 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_auto to
true
2024-12-10 19:26:16.830 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_direct to
true
2024-12-10 19:26:16.830 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_surround
to true
2024-12-10 19:26:16.830 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_ref_stereo
to true
2024-12-10 19:26:16.830 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_dolby to
false
2024-12-10 19:26:16.830 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_dolby to
false
2024-12-10 19:26:16.830 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_dolby to
false
2024-12-10 19:26:16.830 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_dts to
false
2024-12-10 19:26:16.831 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_dts to
false
2024-12-10 19:26:16.831 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_all_stereo
to true
2024-12-10 19:26:16.831 DEBUG (MainThread)
[custom_components.emotiva.emotiva]  Changing visibility of mode_stereo to
true
2024-12-10 19:26:16.831 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Unknown element: menu
2024-12-10 19:26:16.831 DEBUG (MainThread)
[custom_components.emotiva.media_player] Calling
async_schedule_update_ha_state
2024-12-10 19:26:16.836 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Current sound mode Dolby Surround
2024-12-10 19:26:16.837 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Current sound mode Dolby Surround
2024-12-10 19:26:16.838 DEBUG (MainThread)
[custom_components.emotiva.remote] Calling async_schedule_update_ha_state
2024-12-10 19:26:16.839 DEBUG (MainThread)
[custom_components.emotiva.select] Calling async_schedule_update_ha_state
2024-12-10 19:28:06.420 DEBUG (MainThread)
[custom_components.emotiva.emotiva] Connection lost.  Attepting to reconnect
2024-12-10 19:28:06.420 CRITICAL (MainThread)
[custom_components.emotiva.emotiva] Unknown error on command socket
reconnection <class 'AttributeError'>
2024-12-10 19:28:06.421 ERROR (MainThread)
[homeassistant.components.websocket_api.http.connection] [547775514224]
Unexpected exception
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py",
line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in
async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in
_execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line
1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line
1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/emotiva/remote.py", line 118, in
async_turn_on
    await self._device.async_turn_on()
  File "/config/custom_components/emotiva/emotiva.py", line 593, in
async_turn_on
    await self._async_send_emotivacontrol("power_on", "0")
  File "/config/custom_components/emotiva/emotiva.py", line 369, in
_async_send_emotivacontrol
    await self._async_send_request(msg, ack=True, process_response=False)
  File "/config/custom_components/emotiva/emotiva.py", line 355, in
_async_send_request
    await self._udp_client(req, ack)
  File "/config/custom_components/emotiva/emotiva.py", line 341, in
_udp_client
    resp, remote_addr = await self._udp_stream.recv()
                              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'recv'

**Comment by acurafan** [comment] 2024-12-11 23:59
I tried it on github and it would not work. Will this help

**Comment by peteS-UK** [comment] 2024-12-12 10:15
Yes, that's fine.  

`[custom_components.emotiva.emotiva] Cannot connect listener socket 98: Address in use
`

is because it's trying to set up 2 listeners for notifications rather than 1 shared one.  As I thought, I didn't get to the point of moving the listener out of the device setup to be shared by all devices.  I'm just in the midst of setting up a new machine so I should be able to take a look at this next week with a bit of luck.

**Comment by acurafan** [comment] 2024-12-12 10:37
Okay, Thanks

**Comment by peteS-UK** [comment] 2024-12-16 21:51
Hi Larry.  OK, I have a version which might work - or at least it now has a chance of working as I've moved the listeners out of the media player objects up to the integration level.  I've also done some work to the config flow to try and make it support more than one processor in discovery (but that bit definitely needs more work as it's not really done the way HA expects) - just to try and test some stuff.  If I post the zip file here, are you OK to SSH into you HA server and overwrite the version you currently have, or do you need me to post a beta version to HACS (not done that before, so not sure what's involved until I look).  I can't test the two processor stuff, but at least now it doesn't error if I add a second processor manually as if I had one.

**Comment by acurafan** [comment] 2024-12-17 00:57
Hi Pete
Never tried to overwrite in ssh before. I can try with a little instruction. Thanks for your help

**Comment by peteS-UK** [comment] 2024-12-17 09:29
OK, probably more simple to sort out the HACS pre-release approach then tbh.  I had a look and it's nicely buried in HACS 2 - no wonder I couldn't see it anymore...  There's a hidden switch entity...

Go to Settings/Integrations/Entities, select the filter box and turn on disabled and search for emotiva.  You'll see a new switch called Pre-release, which is disabled.  

![image](https://github.com/user-attachments/assets/b54ba35a-86f5-4b5d-b4e1-33952c071db2)


Open this switch, enable it (under the settings cog wheel), wait for it to be enabled, and then turn the switch on.

![image](https://github.com/user-attachments/assets/5dc7541e-69e7-4ec5-9e36-1cf395b313fc)

Now, when I push a pre-release version, HACS will allow you to install it.  If you want to go back, you can download a previous version in the HACS menu by going to the emotiva processor integration, click on the 3 dots top right and then redownload and chose a prior version.  In that menu you can also do "update informaiton" which will make hacs check for new versions - btw, I haven't posted it yet into github - I'll do that later today.

**Comment by peteS-UK** [comment] 2024-12-17 09:51
OK - I just posted a version. If you do an update information, you should see in new version shown in Settings in the normal way to install.

**Comment by acurafan** [comment] 2024-12-17 10:44
Good Morning Added 2nd processor and is working :) Will test further tonight. Thanks Pete

**Comment by peteS-UK** [comment] 2024-12-17 10:47
wow - I suppose I shouldn't be, but I'm pleasantly surprised :-)  It's tricky to do when I can't test.  Key thing will be to see if they get the right feedback - volume and state changes etc..  Could you test the discovery for me as well when you get a chance - delete what you have and then add via discovery - interested to see if it'll manage to find them both.

**Comment by acurafan** [comment] 2024-12-17 10:58
After the update it discovered them both. No manual entry required

**Comment by peteS-UK** [comment] 2024-12-17 11:29
That's good to know.  The discovery at the moment is in the wrong place really - HA wants to do it in the config setup, and then store the discovered entities.  Right now, I just store a "do discovery" sort of thing and then re-discover each time you start,  That does cause some problems - e.g. if you had a conflict with  manual entry, but it seems to work fine so haven't got around to changing it.

**Comment by peteS-UK** [comment] 2024-12-18 20:49
Hi Larry.  I've made a couple of (minor) changes to the version I posted, but will likely hold of another version until a post a new release, which I'll do in a couple of days unless you come across any problems.  I've been running this for several days (with only 1 processor) and it seems reliable.  Have you found any issues?  Any more feedback on the 2 processor support?  Thanks.

**Comment by acurafan** [comment] 2024-12-18 23:47
Hi Pete. It has been solid. No issues to report :) I have been using the send command for different sources ie analog balanced in etc. Any way to incorporate more sources? 😁

**Comment by peteS-UK** [comment] 2024-12-19 00:01
Glad to hear it's been solid.  I'm not sure what you mean by more sources.  You should see the sources you've configured under the xmc setup/inputs menu.

![image](https://github.com/user-attachments/assets/ebafde74-2c86-4476-803d-19db9543bdc4)

Are you not seeing the source list?

**Comment by acurafan** [comment] 2024-12-19 00:39
I do have sources on the drop down list but there are quite a few not there. I use developers tool and the send command to send sources not on the drop down list

**Comment by peteS-UK** [comment] 2024-12-19 09:31
Yep.  Not a lot I can do about that.  The processors have a concept of sources, which are the things you setup under inputs with names, pairs of audio and video inputs etc.  That's what you see on the list because that's what we get in the status updates.  On the xmc-1, there's 8 sources available.  All of the inputs can be configured into a source.  You can select individual inputs through the dev tools, but these aren't the same as sources.  I could maybe add an Input selector, but that would compete with the source selector i.e. If you choose an input not in source then the source will be blank.

**Comment by acurafan** [comment] 2024-12-19 10:20
Yes I noticed that when you "send" an input the source field is blank. Thanks for all of your help and time on this. Very happy that you took this project on.

**Comment by peteS-UK** [comment] 2024-12-19 19:34
Hi @acurafan Larry.  OK - I think I found a way to add the other inputs.  The processors treat the logical sources (1-8) differently to the rest of the physical inputs, but they actually send notification of the current selection on the same setting ("source").  So, bit of fiddling around I think make it work OK.  The only odd thing is that if you select an input which is in a logical source (e.g. you choose HDMI 1, but HDMI 1 is in the first input you've set up), the logical input is actually selected even though the you choose a physical input.

Anyhow, you should see 2.0.0b1 if you update info.  It also has a couple of fixes on the multi proc side.  Give it a try and let me know.

**Comment by acurafan** [comment] 2024-12-21 00:47
Hey Pete. Everything seems to be working great. Thanks for adding the other inputs as well!

**Comment by peteS-UK** [comment] 2024-12-24 08:51
OK, I'm going to close this one down now and push the new release out of beta.  Any new problems, feel free to raise a new issue.

**Closed as completed by peteS-UK** 2024-12-24 08:51 UTC
